version: '3'
services:

  promo-mongo:
    image: mongo
    container_name: promo-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome
      MONGO_INITDB_DATABASE: promo-local
    ports:
      - 27018:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  burger-promo-app:
    image: michaelruocco/burger-promo:${APP_VERSION}
    container_name: burger-promo-app
    #mem_limit: 2048m
    #mem_reservation: 2048m
    restart: on-failure:3
    ports:
      - 8081:80
    environment:
      - SERVER_PORT=80
      - MONGO_CONNECTION_STRING=mongodb://promo-user:welcome01@promo-mongo:27017/promo-local
    depends_on:
      - promo-mongo