spring:
  application:
    name: burger-promo
  main:
    banner-mode: off
  jpa:
    hibernate.ddl-auto: update

info:
  app:
    name: ${spring.application.name}

management:
  endpoint:
    health:
      show-details: always