spring:
  application:
    name: burger-promo
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/promo
    username: root
    password: welcome
    driver-class-name: com.mysql.cf.jdbc.Driver

info:
  app:
    name: ${spring.application.name}

management:
  endpoint:
    health:
      show-details: always