spring:
  application:
    name: burger-promo
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/promo
    username: root
    password: welcome
    hikari:
      maximumPoolSize: 50
      connectionTimeout: 500

info:
  app:
    name: ${spring.application.name}

management:
  endpoint:
    health:
      show-details: always